// styles.svelte
<style>
  :global(*, *:before, *:after) {
    box-sizing: border-box;
  }

  :global(:root) {
    --black: #000001;
    --white: #FFFFFE;
    --ash: #F2F3F2;
    --kelly: #27AE60;
    --red: #CC0000;

    --rythm: 20px;
    --gutter: calc(var(--rythm)*1.666);
    --radius: 3px;
  }

  :global(html) {
    background-color: var(--black);
  }

  :global(body) {
    font-family: "Inter", sans-serif;
    font-feature-settings: "case", "ss01";
    font-size: var(--rythm);
    line-height: 1.333;
    letter-spacing: -0.014em;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    -webkit-tap-highlight-color: var(--kelly);
    
    color: var(--black);
    background-color: var(--ash);

    margin: 0;
  }

  :global(main) {
    display: block;
    max-width: 42rem;
    margin: 0 auto;
    min-height: 88vh;
    padding: var(--gutter);
    padding: calc(var(--gutter)*2) calc(var(--gutter)) calc(var(--gutter)*3.33);
  }

  :global(article) {
    margin: var(--rythm) 0;
  }

  :global(h1, h2, h3, h4, h5, h6, p) {
    white-space: pre-line;
    margin: 0 0 var(--rythm);
  }

  :global(p:last-child) {
    margin-bottom: 0;
  }

  :global(h1, h2, h3) {
    font-size: calc(var(--rythm)*2);
    font-weight: bold;
    line-height: 1;
    letter-spacing: -0.022em;
  }

  :global(h4, h5, h6) {
    font-size: var(--rythm);
    font-weight: bold;
    line-height: 1;
    margin-bottom: calc(var(--rythm)/2);
  }

  :global(a, button) {
    outline: none;
    cursor: pointer;
    color: inherit;
    text-decoration: none;
    position: relative;
  }

  :global(a:active, button:active) {
    top: 1px;
  }

  :global(ul, ol) {
    margin: 0 0 var(--rythm);
    padding-left: var(--rythm);
  }

  :global(small) {
    font-size: calc(var(--rythm)/1.333);
    line-height: calc(var(--rythm)/1.333);
    letter-spacing: -0.009em;
  }

  :global(code, pre) {
    font-family: monospace;
    font-size: var(--rythm);
    line-height: 1;
    white-space: pre;
  }
</style>

// styles.tsx
import React, { Component, SFC } from 'react'
import { Global, css } from '@emotion/core'

export const font = 'Inter UI, sans-serif'

export const colors = {
  white: 'white',
  black: '#000001',
  ash: '#F2F3F2',
  kelly: '#27AE60',
  red: '#CC0000'
}

export const rythm = 20
export const gutter = rythm * 1.666
export const radius = 3


export const GlobalStyles: SFC<{}> = props => <Global
  styles={css`
    *, *:before, *:after {
      box-sizing: border-box;
    }

    html {
      background-color: ${colors.black};
    }

    body {
      font-family: ${font};
      font-size: ${rythm}px;
      line-height: ${rythm*1.333}px;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
      
      color: ${colors.black};
      background-color: ${colors.ash};

      margin: 0;
    }

    main {
      display: block;
      max-width: 42rem;
      margin: 0 auto;
      min-height: 88vh;
      padding: ${gutter*2}px ${gutter}px ${gutter*3.33}px;
    }

    article {
      margin: ${rythm}px 0;
    }

    h1, h2, h3, h4, h5, h6, p {
      white-space: pre-line;
      margin: 0 0 ${rythm}px;

      &:last-child {
        margin-bottom: 0;
      }
    }

    h1, h2, h3 {
      font-size: ${rythm*2}px;
      font-weight: bold;
      line-height: ${rythm*2}px;
    }

    h4, h5, h6 {
      font-size: ${rythm}px;
      font-weight: bold;
      line-height: ${rythm}px;
      margin-bottom: ${rythm/2}px;
    }

    a, button {
      outline: none;
      cursor: pointer;
      color: inherit;
      text-decoration: none;
      position: relative;
      &:active { top: 1px; }
    }

    ul, ol {
      margin: 0 0 ${rythm}px;
      padding-left: ${rythm}px;
    }
  `}
/>
