// routes/article.svelte
<script>
  import { rich, date } from '../helpers/formatters'
  import { content, locale } from '../stores/content'

  import A from '../components/a'

  export let id
  export let journal_id
  $: article = $content.articles.items.find(article => article.fields.identifier === id)
  $: journal = $content.journals.items.find(journal => journal.fields.identifier === journal_id)
</script>

<h1>{article.fields.title}</h1>
<p>
  {article.fields.excerpt}<br />
  <small>{date(article.fields.publishedDate, undefined, undefined, $locale)}{article.fields.ongoing && ($locale === 'fr-CA' ? ' – En continue' : ' – Ongoing')}</small>
</p>
<article>{@html rich(article.fields.body)}</article>

<br />
<br />
{#if journal}
<A to={`/journals/${journal.fields.identifier}`}>← Back to {journal.fields.title}</A>
{/if}

// routes/article.tsx

import * as React from 'react'
import { PureComponent } from 'react'
import { Link, RouteComponentProps } from 'react-router-dom'
import { Entry } from 'contentful'

import { ContentContext, Journal as ContentJournal, Article as ContentArticle } from '../contexts/content'
import { date, rich } from '../helpers/formatters'
import { A, Spacer } from '../components/text'
import { Helm } from '../components/helm'


interface Props extends RouteComponentProps<{ id: string, journal?: string }> {}
interface State {
  article: Entry<ContentArticle>
  journal?: Entry<ContentJournal>
}


export class Article extends PureComponent<Props, State> {
  static contextType = ContentContext
  context!: React.ContextType<typeof ContentContext>

  constructor(props: Props, context: React.ContextType<typeof ContentContext>) {
    super(props)
    this.state = {
      article: context.content.articles.items.find(article => article.fields.identifier === props.match.params.id),
      journal: context.content.journals.items.find(journal => journal.fields.identifier === props.match.params.journal)
    }
  }

  public render() {
    const { article, journal } = this.state
    return <>
      <Helm title={article.fields.title} description={article.fields.excerpt} />

      <h1>{article.fields.title}</h1>
      <p>{article.fields.excerpt}<br /><small>{date(article.fields.publishedDate, undefined, undefined, this.context.locale)}{article.fields.ongoing && (this.context.locale === 'fr-CA' ? <> – En continue</> : <> – Ongoing</>)}</small></p>
      <article>{rich(article.fields.body)}</article>
      <Spacer />
      {journal && <A to={`/journals/${journal.fields.identifier}`}>← Back to {journal.fields.title}</A>}
    </>
  }
}
