// _src/components/navigation.svelte

<script>
  import { stores } from '@sapper/app'
	const { page } = stores()

  import A from './a'

  export let links = []
</script>

<style>
  nav > nav {
    padding-left: calc(var(--rythm)/2);
  }
</style>

<nav>
  {#each links as link (link.sys.id)}
  {#if link.fields.internalLink}
  <A to="{`${link.fields.internalLink.sys.contentType.sys.id}s/${link.fields.internalLink.fields.identifier}`}" current={$page.path === `/${link.fields.internalLink.sys.contentType.sys.id}s/${link.fields.internalLink.fields.identifier}`}>
    {link.fields.label}
  </A>
  {:else if link.fields.externalLink}
  <A to="{link.fields.externalLink}" external rel="me">
    {link.fields.label}
  </A>
  {/if}
  <br />
  {#if link.fields.subLinks}
  <svelte:self links={link.fields.subLinks} />
  {/if}
  {/each}
</nav>

// components/navigation.tsx
import * as React from 'react'
import { PureComponent } from 'react'
import { Link, NavLink } from 'react-router-dom'
import { Entry } from 'contentful'
import { css } from 'emotion'

import { Link as ContentLink, ContentContext } from '../contexts/content'
import { A } from './text'
import { rythm } from '../styles'


interface Props {
  links: Entry<ContentLink>[]
}
interface State {}

const left = css`
  padding-left: ${rythm/2}px;
`

export class Navigation extends PureComponent<Props, State> {
  static contextType = ContentContext
  context!: React.ContextType<typeof ContentContext>

  render() {
    return <nav>
      {this.props.links && this.props.links.map(link => <React.Fragment key={link.sys.id}>
        {link.fields.internalLink
        && <A
          to={`/${link.fields.internalLink.sys.contentType.sys.id}s/${link.fields.internalLink.fields.identifier}`}>
          {link.fields.label}
        </A>}
        {link.fields.externalLink && <A to={link.fields.externalLink} external rel='me'>
          {link.fields.label}
        </A>}
        <br />
        <div className={left}>{link.fields.subLinks && <Navigation links={link.fields.subLinks} />}</div>
      </React.Fragment>
      )}
    </nav>
  }
}
