// components/overlay.svelte
<script>
  import { fade } from 'svelte/transition'

  import Button from './button'

  export let visible = false
  export let button

  let origin = {
    x: 0.5,
    y: 0.5
  }

  function hide() {
    visible = false
  }

  function toggle(e) {
    visible = !visible
  }
</script>

<style>
  aside {
    display: flex;
    justify-content: center;
    align-items: center;

    position: fixed;
    top: 0;
    left: 0;
    z-index: 666;

    width: 100vw;
    height: 100vh;
    overflow-y: auto;
  }

  @media all and (max-width:988px) {
    aside {
      align-items: flex-start;
    }

    div {
      margin-top: var(--rythm);
    }
  }

  aside > button {
    position: relative;
    display: inline-block;
    position: fixed;
    top: 0;
    left: 0;

    width: 100%;
    height: 100%;
    z-index: -1;

    background: var(--white);
    opacity: 0.666;
    border: none;
  }

  div {
    position: relative;
    width: 100%;
    max-width: calc(var(--rythm)*30);
    padding: calc(var(--rythm)*2);

    font-size: calc(var(--rythm)/1.1);
    color: var(--white);
    background-color: var(--black);
    border: 2px solid var(--white);
    border-radius: var(--radius);
  }

  div > button:first-of-type {
    position: absolute;
    top: 0;
    right: 0;
    display: inline-block;
    padding: calc(var(--rythm)/1.666);

    font-size: var(--rythm);
    font-weight: bold;
    background: transparent;
    border: none;
  }
</style>

{#if button}
<Button on:click={toggle}>{button}</Button>
{/if}
{#if visible}
<aside>
  <button on:click|preventDefault={hide} />
  <div style="{`transform-origin: ${origin.x*100}% ${origin.y*100}%`}">
    <button on:click|preventDefault={hide}>✕</button>
    <slot />
  </div>
</aside>
{/if}

// components/overlay.tsx

import * as React from 'react'
import { PureComponent } from 'react'
import { css } from 'emotion'

import { Button, Props as ButtonProps } from './button'
import { colors, rythm, radius } from '../styles'
// import { Glide, Fade } from './animations'

interface Props {
  visible?: boolean
  wider?: boolean
  button?: string | JSX.Element
  buttonProps?: ButtonProps
  onHide?: Function
}
interface State {
  visible: boolean
}

export class Overlay extends PureComponent<Props, State> {

  constructor(props: Props) {
    super(props)
    this.state = {
      visible: props.visible || false
    }
  }

  componentDidMount() {
    document.documentElement.classList.remove('noscroll')
  }

  public toggle() {
    this.setState({visible: !this.state.visible})
    document.documentElement.classList.toggle('noscroll')
  }

  public hide() {
    this.setState({visible: false})
    document.documentElement.classList.remove('noscroll')
    this.props.onHide && this.props.onHide()
  }

  public styles = {
    overlay: css`
      display: flex;
      justify-content: center;
      align-items: center;

      position: fixed;
      top: 0;
      left: 0;
      z-index: 666;

      width: 100vw;
      height: 100vh;
      overflow-y: auto;
    `,
    back: css`
      position: relative;
      display: inline-block;
      position: fixed;
      top: 0;
      left: 0;

      width: 100%;
      height: 100%;
      z-index: -1;

      background: ${colors.white};
      opacity: 0.666;
      border: none;
    `,
    container: css`
      position: relative;
      width: 100%;
      max-width: ${rythm*33}px;
      padding: ${rythm*2}px;
      color: ${colors.white};
      background-color: ${colors.black};
      border: 2px solid ${colors.white};
      border-radius: ${radius*2}px;
    `,
    wider: css`
      max-width: ${rythm*42}px;
    `,
    close: css`
      position: absolute;
      top: 0;
      right: 0;
      display: inline-block;
      padding: ${rythm/1.666}px;

      font-size: ${rythm}px;
      font-weight: bold;
      background: transparent;
      border: none;

      &:hover,
      &:focus {
        top: -1px;
      }

      &:active {
        top: 0px;
      }
    `
  }

  public render() {
    return <>
      {this.props.button && <Button {...this.props.buttonProps} onClick={()=> this.toggle()}>{this.props.button}</Button>}
      {this.state.visible
        ? <div className={this.styles.overlay}>
          <button className={this.styles.back} onClick={()=> this.hide()} />
          <div className={`${this.styles.container}${this.props.wider ? ` ${this.styles.wider}` : ''}`}>
            <button className={this.styles.close} onClick={()=> this.hide()}>✕</button>
            {this.props.children}
          </div>
        </div>
        : null}
    </>
  }
}
