// components/footer.tsx
import React, { SFC } from 'react'
import { css } from 'emotion'

import { ContentContext } from '../contexts/content'

import { rythm, colors, gutter } from '../styles'
import { Navigation } from './navigation'
import { Flex, Third, full, breakpoints } from './layout'
import { Center } from './text'

const styles = breakpoints(css`
  padding: ${gutter}px;
  color: ${colors.white};
  background-color: ${colors.black};
`, {
  phone: css`
    padding-left: ${gutter/2}px;
  `
})

export const Footer: SFC<{}> = props => {
  return <ContentContext.Consumer>
    {({ content }) => <footer className={styles}>
      <Flex spaced middle>
        <Third phone={full}><Navigation links={content.footer.fields.links} /></Third>
        <Center><strong>{content.footer.fields.tagline}</strong><br />{content.footer.fields.copyright}</Center>
        <Third></Third>
      </Flex>
    </footer>}
  </ContentContext.Consumer>
}

// _src/components/footer.svelte
<script>
  import { stores } from '@sapper/app'
	const { page, session } = stores()

  import Flex from './flex'
  import Navigation from './navigation'

  $: footer = $session.navigation.footer
  $: locale = $session.locale
</script>

<style>
  footer {
    padding: var(--gutter);
    color: var(--white);
    background-color: var(--black);
  }

  @media all and (max-width:666px) {
    center {
      text-align: left;
      padding-top: calc(var(--gutter)/2);
    }
  }
</style>

<footer>
  <Flex spaced middle thirds>
    <Navigation links={footer.fields.links} />
    <center><strong>{footer.fields.tagline}</strong><br />{footer.fields.copyright}</center>
    <div />
  </Flex>
</footer>
